### PR TITLE
fix(encode): allow source to be null

### PR DESCRIPTION
**Pull request by richardschneider**
Simple improvement to `encode`.  Needed by https://github.com/ipfs/js-ipfs/issues/1066

### CODE REVIEW

**Comment by dcousens** [comment]
@richardschneider that is absolutely not our problem.
I can't think of a valid reason to change our type signature from `encode :: Buffer -> String` to `encode :: Maybe Buffer -> String`

**Comment by richardschneider** [comment]
As much as I like Haskell, this is JS which is not type safe and `Maybe` is not defined.

Yes, I agree we might have an issue deep in our stack, but I thought you might like this guard, since you are already special casing buffer of length zero.

If you disagree, feel free to close the PR.  After all its your project.

**Comment by dcousens** [comment]
> since you are already special casing buffer of length zero.

That is less of a type special case,  and more of an optimisation,  the result would be the same without it.

> As much as I like Haskell, this is JS which is not type safe and Maybe is not defined.

I used Haskell type syntax,  yes,  but it was only for describing the type notation of what we're doing;  with Javascript types.

> If you disagree, feel free to close the PR. After all its your project.

It isn't my project,  it is @cryptocoinjs/owners :+1: ,  I think I'd rather a second opinion first before closing entirely,  but it does seem like you are catching potential type issues in your stack by trying to return something meaningful,  when `null` doesn't actually have a meaningful representation for `encode(...)`.

**Comment by richardschneider** [comment]
I do agree with you, there is something smelly in my stack. 

I have no emotional investment is this PR.  It's up to you guys.

**Pull request closed without merging**
