### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by rtbz**
Changed var -> let, added case for null & undefined.

### CODE REVIEW

**Comment by fanatid** [comment]
- https://caniuse.com/#feat=let `let` available only for ~80% of users
- `const` should be used if value is not changed, `const` available only from node 6.0.0 http://node.green/#ES2015-bindings-const
- a lot of libraries which uses this project, do not use `let`/`const`
- we use http://standardjs.com/ as linter

**Comment by dcousens** [comment]
> added case for null & undefined.

Please see https://github.com/cryptocoinjs/base-x/pull/44

**Comment by rtbz** [comment]
Here's an updated version passing all 224/224 tests + the standard linter:
https://raw.githubusercontent.com/rtbz/base-x/master/index.js

If null & undefined are to be supported and let / const are to be avoided, would it make sense to test against them and tighten the linter rules?

**Comment by dcousens** [comment]
> If null & undefined are to be supported

They aren't,  that was my point.

Eventually `let / const` will,  but not until Node LTS >= 6

**Pull request closed without merging**
