### PR TITLE
support delimited alphabets of variable length

### PR DESCRIPTION
**Pull request by dcousens**
Follow up to https://github.com/cryptocoinjs/base-x/pull/39

Review / discuss

TODO:
- [ ] Add README spec
- [ ] Improve Errors to use `name` rather than `BASE` (the length) (backwards compatible)

### CODE REVIEW

**Comment by dcousens** [comment]
Actually... on second thought and testing.

This is pointless?

The compression is so bad even for an alphabet of 10,000 words.
We'd need to scale the decoding algorithm to use an appropriate word-size based on the alphabet rather than just 8 bits for this to be effective.

As is,  this just isn't made for this.

I've reverted #39 and merged it into this.

**Comment by dcousens** [comment]
@homeopatchy what were you hoping for in your fork?

**Comment by homeopatchy** [comment]
I forked this module to use it with an implementation of a custom-made phonetic encoding, which uses a set of two-letter phonemes:

```javascript
#!/usr/bin/env node
const stdin = require('/usr/local/lib/node_modules/get-stdin')
const basex = require('/usr/local/lib/node_modules/var-char-len-base-x')

const basep = [
  "ba", "be", "bi", "bo", "bu",
  "ca", "ce", "ci", "co", "cu",
  "fa", "fe", "fi", "fo", "fu",
  "ga", "ge", "gi", "go", "gu",
  "ha", "he", "hi", "ho", "hu",
  "ja", "je", "ji", "jo", "ju",
  "la", "le", "li", "lo", "lu",
  "ma", "me", "mi", "mo", "mu",
  "na", "ne", "ni", "no", "nu",
  "pa", "pe", "pi", "po", "pu",
  "ra", "re", "ri", "ro", "ru",
  "sa", "se", "si", "so", "su",
  "ta", "te", "ti", "to", "tu",
  "wa", "we", "wi", "wo", "wu",
  "xa", "xe", "xi", "xo", "xu"
]

const bsp = basex(basep)

const encode = s => bsp.encode(new Buffer(s, 'hex'))
  .match(/.{1,4}/g).join(' ')

stdin().then((str) => process.stdout.write(encode(str)))
```

Example usage:

```shell
$ hexdump -n 16 -e '4/4 "%08x" 1 ""' /dev/random | hex2phoneme
bope naho moxo sogi fufa jepi jato neji wujo tari cu%
```

Personally I didn't think anybody else would find this useful, but now we're here I guess this allows the module to cover more use cases.

**Comment by homeopatchy** [comment]
After a couple fixes (related to padding) and some optimization, my version performance is similar to this version:

```shell
var-char-len-base-x $ SEED=4439ebb95727b598013dfff39cb2dd69 node benchmark/index.js
Seed: 4439ebb95727b598013dfff39cb2dd69
--------------------------------------------------
encode x 121,068 ops/sec ±2.21% (9 runs sampled)
decode x 287,574 ops/sec ±3.17% (9 runs sampled)
==================================================
```

```shell
base-x $ SEED=4439ebb95727b598013dfff39cb2dd69 node benchmark/index.js
Seed: 4439ebb95727b598013dfff39cb2dd69
--------------------------------------------------
encode x 112,368 ops/sec ±2.49% (9 runs sampled)
decode x 289,725 ops/sec ±3.69% (9 runs sampled)
==================================================
```

**Comment by dcousens** [comment]
Leaving the branch there - for this to be useful,  someone more motivated would need to:

> We'd need to scale the algorithm to use an appropriate word-size based on the alphabet size rather than just 8 bits for this to be effective.

**Pull request closed without merging**
