### PR TITLE
remove extra lines, tape instead mocha, add isValid

### PR DESCRIPTION
**Pull request by fanatid**

### CODE REVIEW

**Comment by jprichardson** [comment]
This brings in unrelated changes - can we split this PR up?

**Comment by fanatid** [comment]
yes, I can do this, I made all in PR because new depends from old
all this conceptually ACK?

**Comment by jprichardson** [comment]
Yeah, conceptual ACK from me. I don't think we need to test Node `0.11` though.

**Comment by fanatid** [comment]
Moved: #21 #22

**Pull request closed without merging**
